**Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [2]:
import numpy as np
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [9]:
print(a.reshape(3,4))
print(a.reshape(4,3))
print(a.reshape(2,6))
print(a.reshape(6,2))
print(a.reshape(12,1))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [12]:
print(a.reshape(12,-1))
print(a.reshape(4,-1))
print(a.reshape(2,-1))
print(a.reshape(-1,2))
print(a.reshape(-1,6))

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [ ]:
#В numpy это двумерный массив, но вообще вектор-столбец - это одномерная структура.

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [14]:
b = np.random.randn(3, 4)

print(b)

print(b.flatten())

[[-1.12184297  0.04205186 -0.72578478 -0.04504988]
 [ 0.32974607 -0.01735858  0.38781296 -0.22705837]
 [ 0.40168102  0.05979939  1.1244522   0.72678001]]
[-1.12184297  0.04205186 -0.72578478 -0.04504988  0.32974607 -0.01735858
  0.38781296 -0.22705837  0.40168102  0.05979939  1.1244522   0.72678001]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [16]:
a = np.arange(20,0,-2)
print(a)
b = np.array([20, 18, 16, 14, 12, 10, 8, 6, 4, 2])
print(b)

[20 18 16 14 12 10  8  6  4  2]
[20 18 16 14 12 10  8  6  4  2]


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [18]:
n=3
a = np.zeros((n-1, 2))
b = np.ones((n, 2))

c = np.vstack((a, b))
print(c)

print(c.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [19]:
a = np.arange(12)
print(f'a = {a}')
A = a.reshape(4,3)
print(f'A = {A}')

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
A = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [65]:
At = A.transpose()
print(f'At = {At}')

B = A.dot(At)
print(f'B = {B}')

print(f'Размер матрицы B = {B.size}')

At = [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
B = [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B = 16


In [66]:
#Поскольку определитель матрцы В равен 0, нельзя вычислить её обратную матрицу (по аналогии с невозможностью деления на 0)
np.linalg.det(B)

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [67]:
np.random.seed(42)
c = np.arange(16)
print(f'c = {c}')
C = c.reshape(4,4)
print(f'C = {C}')
D = B + (10*C)
print(f'D = {D}')

c = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
C = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
D = [[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [68]:
print(f'det D = {np.linalg.det(D)}')

D_inv = np.linalg.inv(D)
print(f'D_inv = {D_inv}')

det D = -7.685903354004529e-25
D_inv = [[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


In [69]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [71]:
ind1_B = np.where(D_inv == 1)
ind0_C = np.where(D_inv == 0)
E = np.zeros((4,4))
print(f'B = {B}')
print(f'C = {C}')
E[ind0_C] = C[np.where(D_inv == 0)]
E[ind1_B] = B[np.where(D_inv == 1)]
print(f'E = {E}')

B = [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
E = [[  5.  14.   2.  32.]
 [  4.  50.  86.   7.]
 [ 23.   9.  10. 212.]
 [ 12. 122.  14.  15.]]
